---
steps:
# API Server
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME:$_VERSION',
         '.']
  dir: 'api-server'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP_NAME:$_VERSION' ]
# UI
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME/ui:$_VERSION',
         '.']
  dir: 'ui'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP_NAME/ui:$_VERSION' ]
# Util image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME/util:$_VERSION',
         '.']
  dir: 'google-marketplace/util-image'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP_NAME/util:$_VERSION' ]
#tester  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME/tester:$_VERSION',
         '.']
  dir: 'google-marketplace/apptest/tester'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP_NAME/tester:$_VERSION' ]
# Deployer
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg', 'REGISTRY=gcr.io/$PROJECT_ID',
         '--build-arg', 'TAG=$_VERSION',
         '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME/deployer',
         '-f', 'deployer/Dockerfile',
         '.']
  dir: 'google-marketplace'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP_NAME/deployer']

substitutions:
    _APP_NAME: visulate-for-oracle
    _VERSION: 1.0.10
images: [
  'gcr.io/$PROJECT_ID/$_APP_NAME:$_VERSION',
  'gcr.io/$PROJECT_ID/$_APP_NAME/ui:$_VERSION',
  'gcr.io/$PROJECT_ID/$_APP_NAME/util:$_VERSION',
  'gcr.io/$PROJECT_ID/$_APP_NAME/tester:$_VERSION',
  'gcr.io/$PROJECT_ID/$_APP_NAME/deployer'
]

