---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Values.apiServer.label }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.apiServer.label }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-{{ .Values.apiServer.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.apiServer.port }}
      targetPort: {{ .Values.apiServer.port }}
      name: {{ .Chart.Name }}-{{ .Values.apiServer.label }}
