---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Values.ui.label }}
  labels: &AppDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Chart.Name }}-{{ .Values.ui.label }}
    app: {{ .Chart.Name }}-{{ .Values.ui.label }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels: *AppDeploymentLabels
  template:
    metadata:
      labels: *AppDeploymentLabels
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.ui.label }}
          image: "{{ .Values.ui.image.registry }}/{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          volumeMounts:
            - name: logfiles
              mountPath: /var/log/nginx
          ports:
            - containerPort: {{ .Values.ui.port }}
        # Sidecar containers
        # Echo logs to stdout where Stackdriver can access them
        - name: message-log
          image: "{{ .Values.ui.image.registry }}/{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          args: [/bin/sh, -c, 'tail -n+1 -f /var/log/nginx/*.log']
          volumeMounts:
            - name: logfiles
              mountPath: /var/log/nginx
      volumes:
        - name: logfiles
          emptyDir: {}
