---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Values.ui.label }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.ui.label }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-{{ .Values.ui.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
      name: {{ .Chart.Name }}-{{ .Values.ui.label }}
    - protocol: TCP
      port: {{ .Values.ui.tlsPort }}
      targetPort: {{ .Values.ui.port }}
      name: {{ .Chart.Name }}-{{ .Values.ui.label }}-https
