---

x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  partnerId: visulate-llc-public
  solutionId: visulate-for-oracle

  publishedVersion: '$TAG'
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.

  images:
    '':
      properties:
        apiServer.image.repo:
          type: REPO_WITH_REGISTRY
        apiServer.image.tag:
          type: TAG
    ui:
      properties:
        ui.image.repo:
          type: REPO_WITH_REGISTRY
        ui.image.tag:
          type: TAG
    util:
      properties:
        util.image:
          type: FULL
    ubbagent:
      properties:
        ubbagent.image:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  controller.serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: edit
  apiServer.replicas:
    type: integer
    default: 1
    description: Desired number of API server Pods
  ui.replicas:
    type: integer
    default: 1
    description: Desired number of UI Pods
  ui.port:
    type: integer
    default: 80
    description: The network port for UI requests
  ui.tlsPort:
    type: integer
    default: 443
    description: The network port for SSL/TLS requests
  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: tls.base64EncodedPrivateKey
          base64EncodedCertificate: tls.base64EncodedCertificate
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

required:
  - name
  - namespace
  - certificate
