---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Values.apiServerLabel }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.apiServerLabel }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-{{ .Values.apiServerLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.apiServerPort }}
      targetPort: {{ .Values.service.apiServerPort }}
      name: {{ .Chart.Name }}-{{ .Values.apiServerLabel }}
